# Generated by Django 6.0.1 on 2026-02-16 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createfeedback',
            options={'ordering': ['-created_at'], 'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
    ]
