# Generated by Django 6.0.1 on 2026-02-16 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0005_alter_jobapplication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMembersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='career.jobpositions')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
