# Generated by Django 6.0.1 on 2026-02-16 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_jobapplication_job'),
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembersmodel',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_members', to='career.jobpositions', unique=True),
        ),
        migrations.AlterField(
            model_name='teammembersmodel',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
