# Generated by Django 6.0.1 on 2026-02-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourteam', '0002_alter_teammembersmodel_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembersmodel',
            name='position',
            field=models.CharField(choices=[('site_supervisor', 'Site Supervisor'), ('technical_manager', 'Technical Manager'), ('construction_worker', 'Construction Worker'), ('office_administrator', 'Office Administrator')], max_length=50),
        ),
    ]
