# Generated by Django 6.0.1 on 2026-01-28 20:20

import career.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[career.validators.name_validator])),
                ('last_name', models.CharField(max_length=50, validators=[career.validators.name_validator])),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(validators=[career.validators.check_number_length, career.validators.check_if_its_digits, career.validators.phone_number_code_validator])),
                ('description', models.TextField()),
            ],
        ),
    ]
