# Generated by Django 6.0.1 on 2026-02-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_submitted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Contact inquiry', 'verbose_name_plural': 'Contact inquiries'},
        ),
    ]
