# Generated by Django 6.0.1 on 2026-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ourteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Facade Works', 'Facade Works'), ('Insulation', 'Insulation'), ('Plastering', 'Plastering'), ('Renovation', 'Renovation'), ('Roof Repair', 'Roof Repair'), ('Sewer Construction', 'Sewer Construction')], max_length=50)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('overview_image', models.ImageField(upload_to='static/images/services')),
                ('detail_view_image', models.ImageField(upload_to='static/images/services')),
                ('responsible_person', models.ManyToManyField(related_name='services', to='ourteam.teammembersmodel')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
