# Generated by Django 6.0.1 on 2026-01-23 20:49

import django.db.models.deletion
from django.db import migrations, models

import common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('site_supervisor', 'Site Supervisor'), ('technical_manager', 'Technical Manager'), ('construction_worker', 'Construction Worker'), ('office_administrator', 'Office Administrator')], max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('location', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract')], default='full_time', max_length=50)),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[common.validators.name_validator])),
                ('second_name', models.CharField(max_length=100, validators=[common.validators.name_validator])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, validators=[common.validators.check_number_length,
                                                                      common.validators.check_if_its_digits,
                                                                      common.validators.phone_number_code_validator])),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='career.jobpositions')),
            ],
        ),
    ]
