# Generated by Django 6.0.1 on 2026-01-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='jobpositions',
            options={'verbose_name': 'Job Position', 'verbose_name_plural': 'Job Positions'},
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_hired',
            field=models.CharField(choices=[('Hired', 'Hired'), ('Not hired', 'Not hired')], default='Not hired', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobpositions',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobpositions',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
