# Generated by Django 6.0.1 on 2026-01-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0002_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
