# Generated by Django 6.0.1 on 2026-01-29 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_rename_second_name_jobapplication_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
