# Generated by Django 6.0.1 on 2026-01-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_rename_phone_jobapplication_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='career.jobpositions'),
        ),
    ]
